name: Build Zotify

on: workflow_dispatch

jobs:
  build-catbot:
    name: Build Zotify
        
    runs-on: windows-latest                      
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Setup Python environment 
      uses: actions/setup-python@v5
      with: 
        python-version: 3.12
          
    - name: Install PyInstaller 
      run: pip install -U pyinstaller
        
    - name: Install required libraries
      run: pip install -r zotify/requirements.txt && pip install git+https://github.com/kokarare1212/librespot-python
    
    - name: Run PyInstaller
      run: pyinstaller --onefile -F zotify\zotify\__main__.py

    - name: Rename Zotify executable
      run: Rename-Item -Path dist\__main__.exe -NewName Zotify.exe
       
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Zotify
        path: dist/Zotify.exe